project:
  type: website
  output-dir: docs

website:
  favicon: images/Aidan Robertson.png
  navbar:
   title: "aidan robertson"
   right:
      - href: index.qmd
        text: home
      - fieldwork.qmd
      - srb.qmd
      - music.qmd
      - icon: github
        href: https://github.com/aidan-robertson
        target: _blank
    
format:
  html:
    theme:
      - quartz
      - styles.scss
    mainfont: Sen
    toc: true
    page-layout: full

editor: visual

