project:
  type: website
  output-dir: docs

website:
  navbar:
   title: "aidan robertson"
   left:
      - href: index.qmd
        text: home
      - fieldwork.qmd
      - srb.qmd
      - movies.qmd
      

format:
  html:
    theme: quartz
    css: styles.css
    toc: true
    page-layout: full

editor: visual

